/**
 * TO AVOID MARGE CONFLICKETS WE ARE GOING TO 
 * USE A MODULER VERSION OF GULP TASKS
 * DO NOT EDIT THIS FILE 
 * IF YOU WANT TO CREATE TASKS THEN PLEASE 
 * CREATE THAT INSIDE THE "/TOOLS/TASKS/" DIR
 * ALL FILES UNDER THIS DIR WITH A **.task.js EXTENTION WILL BE'
 * INCLUDED IN THIS MAIN TASK FILE
 * AND WE WILL USE THIS FILE TO CONNECT THOSE TASKS ONLY
 * 
 * @version 3.0.0
 * @author AVIJIT SARKAR  <https://twitter.com/inset_>
 * Created on : 2018-08-16 22:53:58
 * GMT+0530 (India Standard Time)
 */
'use strict';

 const
    
    gulp = require("gulp"),
    // this thing will help us to connect all our tasks
    HubRegistry = require("gulp-hub")
 ;

 var hub = new HubRegistry(["TOOLS/TASKS/**.task.js"]);

 // registaring all the tasks
 gulp.registry(hub);